const PostsActionTyes = {
  FETCH_POSTS_ADD: 'FETCH_POSTS_ADD',
  FETCH_POSTS_START: 'FETCH_POSTS_START',
  FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',

  FETCH_SINGLE_POSTS_SUCCESS: 'FETCH_SINGLE_POSTS_SUCCESS',

  FETCH_SINGLE_POSTS_COLLECTION_SUCCESS:
    'FETCH_SINGLE_POSTS_COLLECTION_SUCCESS',

  FETCH_SINGLE_HIGHLIGHT_POSTS_COLLECTION_SUCCESS:
    'FETCH_SINGLE_HIGHLIGHT_POSTS_COLLECTION_SUCCESS',

  FETCH_USERNAME_POSTS_ADD: 'FETCH_USERNAME_POSTS_ADD',
  FETCH_USERNAME_POSTS_START: 'FETCH_USERNAME_POSTS_START',
  FETCH_USERNAME_POSTS_SUCCESS: 'FETCH_USERNAME_POSTS_SUCCESS',
  FETCH_USERNAME_POSTS_DOWNLOAD: 'FETCH_USERNAME_POSTS_DOWNLOAD',

  FETCH_HASHTAG_POSTS_ADD: 'FETCH_HASHTAG_POSTS_ADD',
  FETCH_HASHTAG_POSTS_START: 'FETCH_HASHTAG_POSTS_START',
  FETCH_HASHTAG_POSTS_SUCCESS: 'FETCH_HASHTAG_POSTS_SUCCESS',
  FETCH_HASHTAG_POSTS_DOWNLOAD: 'FETCH_HASHTAG_POSTS_DOWNLOAD',

  FETCH_HASHTAG_POSTS_ADD: 'FETCH_HASHTAG_POSTS_ADD',
  FETCH_HASHTAG_POSTS_START: 'FETCH_HASHTAG_POSTS_START',
  FETCH_HASHTAG_POSTS_SUCCESS: 'FETCH_HASHTAG_POSTS_SUCCESS',
  FETCH_HASHTAG_POSTS_DOWNLOAD: 'FETCH_HASHTAG_POSTS_DOWNLOAD',

  FETCH_HIGHLIGHT_POSTS_ADD: 'FETCH_HIGHLIGHT_POSTS_ADD',
  FETCH_HIGHLIGHT_POSTS_START: 'FETCH_HIGHLIGHT_POSTS_START',
  FETCH_HIGHLIGHT_POSTS_SUCCESS: 'FETCH_HIGHLIGHT_POSTS_SUCCESS',
  FETCH_HIGHLIGHT_POSTS_DOWNLOAD: 'FETCH_HIGHLIGHT_POSTS_DOWNLOAD',

  FETCH_STORY_POSTS_ADD: 'FETCH_STORY_POSTS_ADD',
  FETCH_STORY_POSTS_START: 'FETCH_STORY_POSTS_START',
  FETCH_STORY_POSTS_SUCCESS: 'FETCH_STORY_POSTS_SUCCESS',

  // FETCH_SINGLE_POSTS_SUCCESS: 'FETCH_SINGLE_POSTS_SUCCESS',
};

export default PostsActionTyes;
