const SoundCloudActionTypes = {
  CLEAR_SOUNDCLOUD_DATA: 'CLEAR_SOUNDCLOUD_DATA',
  SET_SOUNDCLOUD_USER: 'SET_SOUNDCLOUD_USER',
  SOUNDCLOUD_VIDEO_START: 'SOUNDCLOUD_VIDEO_START',
  SOUNDCLOUD_VIDEO_FAILURE: 'SOUNDCLOUD_VIDEO_FAILURE',
  SOUNDCLOUD_VIDEO_SUCCESS: 'SOUNDCLOUD_VIDEO_SUCCESS',
};

export default SoundCloudActionTypes;
