const TwitterActionTypes = {
  CLEAR_TWITTER_DATA: 'CLEAR_TWITTER_DATA',
  TWITTER_VIDEO_START: 'TWITTER_VIDEO_START',
  TWITTER_VIDEO_FAILURE: 'TWITTER_VIDEO_FAILURE',
  TWITTER_VIDEO_SUCCESS: 'TWITTER_VIDEO_SUCCESS',
};

export default TwitterActionTypes;
