const FacebookActionTypes = {
  CLEAR_FACEBOOK_DATA: 'CLEAR_FACEBOOK_DATA',
  FACEBOOK_VIDEO_START: 'FACEBOOK_VIDEO_START',
  FACEBOOK_VIDEO_FAILURE: 'FACEBOOK_VIDEO_FAILURE',
  FACEBOOK_VIDEO_SUCCESS: 'FACEBOOK_VIDEO_SUCCESS',
};

export default FacebookActionTypes;
