const InstagramActionTypes = {
  CLEAR_YOUTUBE_DATA: 'CLEAR_YOUTUBE_DATA',
  FETCH_VIDEO_START: 'FETCH_VIDEO_START',
  FETCH_VIDEO_FAILURE: 'FETCH_VIDEO_FAILURE',
  FETCH_VIDEO_SUCCESS: 'FETCH_VIDEO_SUCCESS',

  FETCH_VIDEO_DOWNLOAD_START: 'FETCH_VIDEO_DOWNLOAD_START',
  FETCH_VIDEO_DOWNLOAD_FAILURE: 'FETCH_VIDEO_DOWNLOAD_FAILURE',
  FETCH_VIDEO_DOWNLOAD_SUCCESS: 'FETCH_VIDEO_DOWNLOAD_SUCCESS',

  // FETCH_SINGLE_POSTS_SUCCESS: 'FETCH_SINGLE_POSTS_SUCCESS',
  // SET_DOWNLOAD_DATA: 'SET_DOWNLOAD_DATA',
  // SAVE_DOWNLOAD: 'SAVE_DOWNLOAD',
  // GET_DOWNLOAD: 'GET_DOWNLOAD',
  // GET_SUBSCRIPTION: 'GET_SUBSCRIPTION',
};

export default InstagramActionTypes;
