const YoutubeActionTypes = {
  CLEAR_YOUTUBE_DATA: 'CLEAR_YOUTUBE_DATA',
  YOUTUBE_VIDEO_START: 'YOUTUBE_VIDEO_START',
  YOUTUBE_VIDEO_FAILURE: 'YOUTUBE_VIDEO_FAILURE',
  YOUTUBE_VIDEO_SUCCESS: 'YOUTUBE_VIDEO_SUCCESS',
};

export default YoutubeActionTypes;
