const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',

  SET_TOKEN: 'SET_TOKEN',
  SET_DOWNLOADS: 'SET_DOWNLOADS',
  SET_SUBSCRIPTION: 'SET_SUBSCRIPTION',
  SET_MESSAGE: 'SET_MESSAGE',

  USER_PAYMENT_START: 'USER_PAYMENT_START',
  USER_PAYMENT_SUCCESS: 'USER_PAYMENT_SUCCESS',

  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_IN_BY_TOKEN_START: 'SIGN_IN_BY_TOKEN_START',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
};


export default UserActionTypes;
