const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  CLEAR_DATA: 'CLEAR_DATA',

  SET_TOKEN: 'SET_TOKEN',
  SET_DOWNLOADS: 'SET_DOWNLOADS',
  SET_SUBSCRIPTION: 'SET_SUBSCRIPTION',
  SET_MESSAGE: 'SET_MESSAGE',
  SET_PAYMENT_DATA: 'SET_PAYMENT_DATA',
  SET_LOADING: 'SET_LOADING',

  USER_PAYMENT_START: 'USER_PAYMENT_START',
  USER_PAYMENT_SUCCESS: 'USER_PAYMENT_SUCCESS',
  USER_PAYMENT_FAILURE: 'USER_PAYMENT_FAILURE',

  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_IN_BY_TOKEN_START: 'SIGN_IN_BY_TOKEN_START',

  RESEND_CONFIRM_EMAIL_START: 'RESEND_CONFIRM_EMAIL_START',
  RESEND_CONFIRM_EMAIL_SUCCESS: 'RESEND_CONFIRM_EMAIL_SUCCESS',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',

  FORGET_PASSWORD_START: 'FORGET_PASSWORD_START',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',

  RESET_PASSWORD: 'RESET_PASSWORD',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
};

export default UserActionTypes;
